# Generated by Django 6.0.7 on 2026-07-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_reset',
            field=models.BooleanField(default=False, help_text='Force user to reset password on next login'),
        ),
    ]
