# Generated by Django 6.0.7 on 2026-07-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_force_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='encryption_key',
            field=models.CharField(default='', help_text='Fernet encryption key for encrypting configs/secrets for this client', max_length=255),
        ),
    ]
