# Generated by Django 6.0.7 on 2026-07-29 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_serviceclient_encryption_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Provider name (e.g., 'Google', 'GitHub', 'Okta')", max_length=120, unique=True)),
                ('client_id', models.CharField(help_text='OAuth2 Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='OAuth2 Client Secret', max_length=255)),
                ('authorization_url', models.URLField(help_text='Authorization endpoint URL (for user login)', max_length=500)),
                ('token_url', models.URLField(help_text='Token endpoint URL', max_length=500)),
                ('userinfo_url', models.URLField(blank=True, help_text='Userinfo endpoint URL (OIDC)', max_length=500, null=True)),
                ('scope', models.CharField(default='openid email profile', help_text='OAuth2 scopes (space-separated)', max_length=255)),
                ('supported_flows', models.CharField(choices=[('authorization_code', 'Authorization Code (for Users)'), ('client_credentials', 'Client Credentials (for Service Clients)'), ('both', 'Both Flows')], default='both', help_text='Which OAuth2 flows this provider supports', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_create_users', models.BooleanField(default=True, help_text='Automatically create users on first OAuth login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OAuth Provider',
                'verbose_name_plural': 'OAuth Providers',
                'db_table': 'oauth_providers',
            },
        ),
        migrations.CreateModel(
            name='OAuthServiceClientToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_tokens', to='authentication.oauthprovider')),
                ('service_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='authentication.serviceclient')),
            ],
            options={
                'verbose_name': 'OAuth Service Token',
                'verbose_name_plural': 'OAuth Service Tokens',
                'db_table': 'oauth_service_tokens',
                'unique_together': {('service_client', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='OAuthUserToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token', null=True)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_user_id', models.CharField(help_text='User ID from OAuth provider', max_length=255)),
                ('provider_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to='authentication.oauthprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OAuth User Token',
                'verbose_name_plural': 'OAuth User Tokens',
                'db_table': 'oauth_user_tokens',
                'indexes': [models.Index(fields=['provider_user_id', 'provider'], name='oauth_user__provide_625fc3_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
