# Generated by Django 6.0.7 on 2026-07-29 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_oauthprovider_oauthserviceclienttoken_oauthusertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthprovider',
            name='supported_flows',
        ),
        migrations.DeleteModel(
            name='OAuthServiceClientToken',
        ),
    ]
