# Generated by Django 6.0.7 on 2026-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_service_client_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceclient',
            name='api_key_id',
            field=models.CharField(blank=True, db_index=True, help_text='Public identifier for the service client API key', max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', help_text='Hash of the secret part of the API key', max_length=255),
        ),
    ]
