# Generated by Django 6.0.7 on 2026-07-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_serviceclient_api_key_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='oauthusertoken',
            name='oauth_user__provide_625fc3_idx',
        ),
        migrations.AddIndex(
            model_name='oauthprovider',
            index=models.Index(fields=['is_active', '-created_at'], name='oauth_provi_is_acti_b3a6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthusertoken',
            index=models.Index(fields=['provider', 'provider_user_id'], name='oauth_user__provide_fba250_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclient',
            index=models.Index(fields=['-created_at'], name='service_cli_created_a4de14_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceclient',
            index=models.Index(fields=['is_active', '-created_at'], name='service_cli_is_acti_6274f3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_created_30b417_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', '-created_at'], name='users_is_acti_af9e1a_idx'),
        ),
    ]
