# Generated by Django 6.0.7 on 2026-08-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_oauthusertoken_oauth_user__provide_625fc3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Unset until an admin activates this user. Inactive users cannot log in.'),
        ),
    ]
