package security

import (
	"strings"
	"testing"
)

// Generated by Django's PBKDF2PasswordHasher (1,200,000 iterations, the
// Django 6.0 default) for the plaintext "CorrectHorseBatteryStaple". This
// legacy format is no longer produced by HashPassword but must keep
// verifying indefinitely for hashes created before the argon2id cutover.
const (
	pyPassword = "CorrectHorseBatteryStaple"
	pyHash     = "pbkdf2_sha256$1200000$8YfCGkHU7ijSVyecBxh9Bs$J7iw9S9dHArWC8+mB4Lafd+Y//x6C1l6dPdwVMsO364="
)

func TestVerifyPassword_LegacyPBKDF2Format(t *testing.T) {
	if !VerifyPassword(pyPassword, pyHash) {
		t.Fatal("expected legacy pbkdf2 hash to verify")
	}
	if VerifyPassword("wrong-password", pyHash) {
		t.Fatal("expected wrong password to fail verification")
	}
}

func TestHashAndVerifyPassword_RoundTrip(t *testing.T) {
	hash, err := HashPassword("s3cr3t-api-key")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if !strings.HasPrefix(hash, "argon2id$") {
		t.Fatalf("expected HashPassword to produce an argon2id hash, got %q", hash)
	}
	if !VerifyPassword("s3cr3t-api-key", hash) {
		t.Fatal("expected freshly hashed password to verify")
	}
	if VerifyPassword("not-the-secret", hash) {
		t.Fatal("expected wrong password to fail verification")
	}
}

func TestVerifyPassword_MalformedHash(t *testing.T) {
	cases := []string{
		"",
		"not-a-hash-at-all",
		"pbkdf2_sha256$notanumber$salt$hash",
		"bcrypt$12$salt$hash",
		"argon2id$bogus",
		"argon2id$v=19$m=notanumber,t=2,p=1$c2FsdA$aGFzaA",
		"argon2id$v=19$m=19456,t=2,p=1$not-base64!!$aGFzaA",
	}
	for _, c := range cases {
		if VerifyPassword("anything", c) {
			t.Fatalf("expected malformed hash %q to fail verification", c)
		}
	}
}

func TestIsLegacyHash(t *testing.T) {
	if !IsLegacyHash(pyHash) {
		t.Fatal("expected pbkdf2-format hash to be reported as legacy")
	}
	argon2Hash, err := HashPassword("s3cr3t")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if IsLegacyHash(argon2Hash) {
		t.Fatal("expected argon2id hash to not be reported as legacy")
	}
}
