package security

import "testing"

// Generated by Django's PBKDF2PasswordHasher (1,200,000 iterations, the
// Django 6.0 default) for the plaintext "CorrectHorseBatteryStaple".
const (
	pyPassword = "CorrectHorseBatteryStaple"
	pyHash     = "pbkdf2_sha256$1200000$8YfCGkHU7ijSVyecBxh9Bs$J7iw9S9dHArWC8+mB4Lafd+Y//x6C1l6dPdwVMsO364="
)

func TestVerifyPassword_CrossCompatWithDjango(t *testing.T) {
	if !VerifyPassword(pyPassword, pyHash) {
		t.Fatal("expected Django-produced hash to verify")
	}
	if VerifyPassword("wrong-password", pyHash) {
		t.Fatal("expected wrong password to fail verification")
	}
}

func TestHashAndVerifyPassword_RoundTrip(t *testing.T) {
	hash, err := HashPassword("s3cr3t-api-key")
	if err != nil {
		t.Fatalf("HashPassword: %v", err)
	}
	if !VerifyPassword("s3cr3t-api-key", hash) {
		t.Fatal("expected freshly hashed password to verify")
	}
	if VerifyPassword("not-the-secret", hash) {
		t.Fatal("expected wrong password to fail verification")
	}
}

func TestVerifyPassword_MalformedHash(t *testing.T) {
	cases := []string{
		"",
		"not-a-hash-at-all",
		"pbkdf2_sha256$notanumber$salt$hash",
		"bcrypt$12$salt$hash",
	}
	for _, c := range cases {
		if VerifyPassword("anything", c) {
			t.Fatalf("expected malformed hash %q to fail verification", c)
		}
	}
}
