# Generated by Django 6.0.7 on 2026-07-29 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read')], max_length=20)),
                ('resource', models.CharField(choices=[('user', 'User'), ('config', 'Config'), ('secret', 'Secret'), ('client', 'Service Client'), ('preference', 'Preference'), ('flag', 'Feature Flag')], max_length=50)),
                ('resource_id', models.UUIDField(db_index=True)),
                ('user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
            },
        ),
        migrations.CreateModel(
            name='ConfigEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(db_index=True, max_length=120)),
                ('environment', models.CharField(db_index=True, max_length=120)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('number', 'Number'), ('object', 'Object'), ('array', 'Array')], default='string', max_length=20)),
                ('is_secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Config Entry',
                'verbose_name_plural': 'Config Entries',
                'db_table': 'config_entries',
                'indexes': [models.Index(fields=['service', 'environment'], name='config_entr_service_bca0b6_idx')],
                'unique_together': {('service', 'environment', 'key')},
            },
        ),
    ]
