# Generated by Django 6.0.7 on 2026-07-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user_id',
        ),
        migrations.AddField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='resource_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='resource',
            field=models.CharField(choices=[('user', 'User'), ('config', 'Config'), ('client', 'Service Client'), ('flag', 'Feature Flag'), ('oauth_provider', 'OAuth Provider')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='resource_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read'), ('toggle', 'Toggle'), ('login', 'Login'), ('logout', 'Logout')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['-timestamp', 'resource'], name='activities_timesta_6e38b6_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user_email', '-timestamp'], name='activities_user_em_e374a3_idx'),
        ),
    ]
