# Generated by Django 6.0.7

import uuid
import django.db.models.deletion
from django.db import migrations, models


def backfill_app_env_relations(apps, schema_editor):
    ConfigEntry = apps.get_model("config_management", "ConfigEntry")
    Application = apps.get_model("config_management", "Application")
    Environment = apps.get_model("config_management", "Environment")

    for entry in ConfigEntry.objects.all().iterator():
        app, _ = Application.objects.get_or_create(name=entry.service)
        env, _ = Environment.objects.get_or_create(
            application=app,
            name=entry.environment,
        )
        entry.application = app
        entry.environment_ref = env
        entry.save(update_fields=["application", "environment_ref"])


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0002_remove_activity_user_id_activity_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=120, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="config_management.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Environment",
                "verbose_name_plural": "Environments",
                "db_table": "environments",
                "ordering": ["application__name", "name"],
                "unique_together": {("application", "name")},
            },
        ),
        migrations.AddField(
            model_name="configentry",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_entries",
                to="config_management.application",
            ),
        ),
        migrations.AddField(
            model_name="configentry",
            name="environment_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_entries",
                to="config_management.environment",
            ),
        ),
        migrations.RunPython(backfill_app_env_relations, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="configentry",
            unique_together=set(),
        ),
        migrations.RemoveIndex(
            model_name="configentry",
            name="config_entr_service_bca0b6_idx",
        ),
        migrations.RemoveField(
            model_name="configentry",
            name="service",
        ),
        migrations.RemoveField(
            model_name="configentry",
            name="environment",
        ),
        migrations.RenameField(
            model_name="configentry",
            old_name="environment_ref",
            new_name="environment",
        ),
        migrations.AlterField(
            model_name="configentry",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_entries",
                to="config_management.application",
            ),
        ),
        migrations.AlterField(
            model_name="configentry",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config_entries",
                to="config_management.environment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configentry",
            unique_together={("application", "environment", "key")},
        ),
        migrations.AddIndex(
            model_name="environment",
            index=models.Index(fields=["application", "name"], name="environments_applica_7fb5e9_idx"),
        ),
        migrations.AddIndex(
            model_name="configentry",
            index=models.Index(fields=["application", "environment"], name="config_entr_applica_964b84_idx"),
        ),
        migrations.AlterField(
            model_name="activity",
            name="resource",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("config", "Config"),
                    ("client", "Service Client"),
                    ("flag", "Feature Flag"),
                    ("oauth_provider", "OAuth Provider"),
                    ("application", "Application"),
                    ("environment", "Environment"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
