# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0003_application_environment_and_configentry_fk"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="configentry",
            new_name="config_entr_applica_72d196_idx",
            old_name="config_entr_applica_964b84_idx",
        ),
        migrations.RenameIndex(
            model_name="environment",
            new_name="environment_applica_1fad74_idx",
            old_name="environments_applica_7fb5e9_idx",
        ),
    ]
