# Generated by Django 6.0.7

import django.db.models.deletion
from django.db import migrations, models


def backfill_feature_flag_scope(apps, schema_editor):
    Application = apps.get_model("config_management", "Application")
    Environment = apps.get_model("config_management", "Environment")
    FeatureFlag = apps.get_model("config_management", "FeatureFlag")

    fallback_environment = Environment.objects.select_related("application").order_by(
        "application__name", "name"
    ).first()
    if fallback_environment is None:
        fallback_application, _ = Application.objects.get_or_create(name="global")
        fallback_environment, _ = Environment.objects.get_or_create(
            application=fallback_application,
            name="global",
        )

    for flag in FeatureFlag.objects.all().iterator():
        flag.application = fallback_environment.application
        flag.environment = fallback_environment
        flag.save(update_fields=["application", "environment"])


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0004_rename_generated_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="config_management.application",
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="config_management.environment",
            ),
        ),
        migrations.RunPython(backfill_feature_flag_scope, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="featureflag",
            name="name",
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="config_management.application",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_flags",
                to="config_management.environment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="featureflag",
            unique_together={("application", "environment", "name")},
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["application", "environment", "name"],
                name="feature_fla_applica_352adf_idx",
            ),
        ),
    ]
