# Generated by Django 6.0.7

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_management", "0005_bind_feature_flags_to_application_environment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="featureflag",
            new_name="feature_fla_applica_bd6eba_idx",
            old_name="feature_fla_applica_352adf_idx",
        ),
    ]
