# Generated by Django 6.0.7 on 2026-07-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0006_rename_featureflag_scope_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['resource', 'type', '-timestamp'], name='activities_resourc_5a50e6_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['application', 'environment', 'deleted_at'], name='feature_fla_applica_b48a36_idx'),
        ),
        migrations.AddIndex(
            model_name='featureflag',
            index=models.Index(fields=['deleted_at'], name='feature_fla_deleted_840e8b_idx'),
        ),
    ]
