# Generated by Django 6.0.7 on 2026-07-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0007_activity_activities_resourc_5a50e6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('read', 'Read'), ('toggle', 'Toggle'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('auth_failed', 'Authentication Failed')], db_index=True, max_length=20),
        ),
    ]
