# Generated by Django 6.0.7 on 2026-07-30 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0008_alter_activity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigEntryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('number', 'Number'), ('object', 'Object'), ('array', 'Array')], default='string', max_length=20)),
                ('is_secret', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('rollback', 'Rollback')], max_length=20)),
                ('version', models.PositiveIntegerField()),
                ('changed_by', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config_management.configentry')),
            ],
            options={
                'verbose_name': 'Config Entry Version',
                'verbose_name_plural': 'Config Entry Versions',
                'db_table': 'config_entry_versions',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['config_entry', '-version'], name='config_entr_config__279c0f_idx')],
                'unique_together': {('config_entry', 'version')},
            },
        ),
    ]
